name: Refresh meta
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: eclipse-temurin:17
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew refreshMeta --stacktrace
        env:
          META_UPDATE_URL: ${{ secrets.META_UPDATE_URL }}
