name: Release
on: [workflow_dispatch] # Manual trigger
jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: eclipse-temurin:17
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build publish --stacktrace
        env:
          MAVEN_URL: ${{ secrets.MAVEN_URL }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

      - name: Update Quilt Meta
        uses: quiltmc/update-quilt-meta@main
        with:
          b2-key-id: ${{ secrets.META_B2_KEY_ID }}
          b2-key: ${{ secrets.META_B2_KEY }}
          cf-key: ${{ secrets.META_CF_KEY }}
